name: Deploy to Netlify

on:
  push:
    branches: [ "main" ]

permissions:
  contents: read
  deployments: write
  statuses: write


jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Install Dependencies
        run: npm install
        working-directory: ldc-website
      
      - name: Build Project
        run: |
          cd ldc-website
          npm run build

      - name: Deploy to Netlify
        uses: nwtgck/actions-netlify@v2
        with:
          publish-dir: 'ldc-website/dist'
          production-branch: main
          github-token: ${{ secrets.GITHUB_TOKEN }}
          netlify-auth-token: ${{ secrets.NETLIFY_AUTH_TOKEN }}
          netlify-site-id: ${{ secrets.NETLIFY_SITE_ID }}
          deploy-message: "Send website for Netlify Deployment"